services:
  api1: # API - Instância 01
    image: gustavo/api
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 01
    image: gustavo/api
    hostname: api2
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./docker-compose-files/ngnix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    
  db: # Banco de dados
    image: postgres
    restart: always
    volumes:
      - ./docker-compose-files/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "senhabanco123"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
